# Generated by Django 4.2.5 on 2023-09-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='where habit needs to be complete')),
                ('time', models.TimeField(verbose_name='when the habit needs to be complete')),
                ('action', models.CharField(max_length=150, verbose_name='action that constitutes a habit')),
                ('is_pleasant', models.BooleanField(default=True, verbose_name='is habit is pleasant')),
                ('periodicity', models.SmallIntegerField(default=1, verbose_name='periodicity of habit execution')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='reward for habit complete')),
                ('time_for_complete', models.TimeField(verbose_name='time to complete habit')),
                ('is_public', models.BooleanField(default=True, verbose_name='is habit is public')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='if habit related with another')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'ordering': ['pk'],
            },
        ),
    ]
